<a href="https://colab.research.google.com/github/AswinAzikar/tutedude_assignments/blob/Module_7/m7L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

In [ ]:
np_ht = np.array([74,75,77,76,78])

In [ ]:
type(np_ht)




numpy.ndarray

In [ ]:
np_ht * 4.1

array([303.4, 307.5, 315.7, 311.6, 319.8])

In [ ]:
list1 = [1,2,44,3]
list2 = [32,1,4,1]
list1+ list2

[1, 2, 44, 3, 32, 1, 4, 1]

In [ ]:
np_list1 = np.array(list1)
np_list2 = np.array(list2)
np_list1 + np_list2

array([33,  3, 48,  4])

In [ ]:
players = [
(74, 100),
 (75, 215),
 (77, 210),
 (76, 188),
 (78, 176),
 (79, 175),
 (77, 190),
 (76, 156),
 (74, 180),
 (79, 210),
 (77, 210),
 (71, 176),
 (76, 224),
 (74, 227),
 (75, 232),
 (75, 166),
 (77, 198),
 (75, 166),
 (72, 244),
 (78, 181),
 (79, 225),
 (74, 236),
 (76, 189),
 (77, 245),
 (71, 173),
 (78, 168),
 (70, 206),
 (78, 177),
 (74, 173),
 (75, 155),
 (76, 246),
 (78, 203),
 (71, 162),
 (76, 160),
 (72, 175),
 (77, 166),
 (73, 180),
 (79, 220),
 (78, 238),
 (79, 191),
 (75, 187),
 (73, 160),
 (77, 178),
 (72, 187),
 (71, 159),
 (74, 164),
 (76, 164),
 (78, 186),
 (77, 196),
 (78, 225),
 (72, 150),
 (76, 162),
 (74, 238),
 (74, 193),
 (73, 209),
 (72, 164),
 (73, 151),
 (75, 239),
 (70, 198),
 (73, 202),
 (71, 184),
 (72, 223),
 (74, 173),
 (74, 186),
 (77, 166),
 (75, 153),
 (72, 210),
 (78, 201),
 (75, 184),
 (72, 239),
 (73, 240),
 (74, 159),
 (76, 168),
 (74, 219),
 (74, 233),
 (79, 151),
 (73, 213),
 (78, 166),
 (78, 219),
 (76, 224),
 (71, 154),
 (76, 219),
 (77, 178),
 (73, 239),
 (71, 173),
 (76, 177),
 (79, 237),
 (71, 199),
 (74, 171),
 (70, 176),
 (79, 240),
 (78, 217),
 (71, 232),
 (75, 201),
 (76, 234),
 (78, 160),
 (77, 193),
 (71, 216),
 (70, 243),
 (70, 205),
 (75, 178),
 (75, 183),
 (75, 215),
 (77, 210),
 (76, 188),
 (78, 176),
 (79, 175),
 (77, 190),
 (76, 156),
 (74, 180),
 (79, 210),
 (77, 210),
 (71, 176),
 (76, 224),
 (74, 227),
 (75, 232),
 (75, 166),
 (77, 198),
 (75, 166),
 (72, 244),
 (78, 181),
 (79, 225),
 (74, 236),
 (76, 189),
 (77, 245),
 (71, 173),
 (78, 168),
 (70, 206),
 (78, 177),
 (74, 173),
 (75, 155),
 (76, 246),
 (78, 203),
 (71, 162),
 (76, 160),
 (72, 175),
 (77, 166),
 (73, 180),
 (79, 220),
 (78, 238),
 (79, 191),
 (75, 187),
 (73, 160),
 (77, 178),
 (72, 187),
 (71, 159),
 (74, 164),
 (76, 164),
 (78, 186),
 (77, 196),
 (78, 225),
 (72, 150),
 (76, 162),
 (74, 238),
 (74, 193),
 (73, 209),
 (72, 164),
 (73, 151),
 (75, 239),
 (70, 198),
 (73, 202),
 (71, 184),
 (72, 223),
 (74, 173),
 (74, 186),
 (77, 166),
 (75, 153),
 (72, 210),
 (78, 201),
 (75, 184),
 (72, 239),
 (73, 240),
 (74, 159),
 (76, 168),
 (74, 219),
 (74, 233),
 (79, 151),
 (73, 213),
 (78, 166),
 (78, 219),
 (76, 224),
 (71, 154),
 (76, 219),
 (77, 178),
 (73, 239),
 (71, 173),
 (76, 177),
 (79, 237),
 (71, 199),
 (74, 171),
 (70, 176),
 (79, 240),
 (78, 217),
 (71, 232),
 (75, 201),
 (76, 234),
 (78, 160),
 (77, 193),
 (71, 216),
 (70, 243),
 (70, 205),
 (75, 178),
 (75, 183),
 (72, 239),
 (77, 244),
 (79, 184)]

In [ ]:
len(players)

206

In [ ]:
np_players = np.array(players)
print (np_players)

[[ 74 100]
 [ 75 215]
 [ 77 210]
 [ 76 188]
 [ 78 176]
 [ 79 175]
 [ 77 190]
 [ 76 156]
 [ 74 180]
 [ 79 210]
 [ 77 210]
 [ 71 176]
 [ 76 224]
 [ 74 227]
 [ 75 232]
 [ 75 166]
 [ 77 198]
 [ 75 166]
 [ 72 244]
 [ 78 181]
 [ 79 225]
 [ 74 236]
 [ 76 189]
 [ 77 245]
 [ 71 173]
 [ 78 168]
 [ 70 206]
 [ 78 177]
 [ 74 173]
 [ 75 155]
 [ 76 246]
 [ 78 203]
 [ 71 162]
 [ 76 160]
 [ 72 175]
 [ 77 166]
 [ 73 180]
 [ 79 220]
 [ 78 238]
 [ 79 191]
 [ 75 187]
 [ 73 160]
 [ 77 178]
 [ 72 187]
 [ 71 159]
 [ 74 164]
 [ 76 164]
 [ 78 186]
 [ 77 196]
 [ 78 225]
 [ 72 150]
 [ 76 162]
 [ 74 238]
 [ 74 193]
 [ 73 209]
 [ 72 164]
 [ 73 151]
 [ 75 239]
 [ 70 198]
 [ 73 202]
 [ 71 184]
 [ 72 223]
 [ 74 173]
 [ 74 186]
 [ 77 166]
 [ 75 153]
 [ 72 210]
 [ 78 201]
 [ 75 184]
 [ 72 239]
 [ 73 240]
 [ 74 159]
 [ 76 168]
 [ 74 219]
 [ 74 233]
 [ 79 151]
 [ 73 213]
 [ 78 166]
 [ 78 219]
 [ 76 224]
 [ 71 154]
 [ 76 219]
 [ 77 178]
 [ 73 239]
 [ 71 173]
 [ 76 177]
 [ 79 237]
 [ 71 199]
 [ 74 171]
 [ 70 176]
 [ 79 240]

In [ ]:
type(np_players)

numpy.ndarray

In [ ]:
players[1][1]

215

In [ ]:
np_players.shape

(206, 2)

In [ ]:
np_players.ndim

2

In [ ]:
np_players.dtype

dtype('int64')

In [ ]:
players_conv = np_players * [0.0254 , 0.452]
players_conv

array([[  1.8796,  45.2   ],
       [  1.905 ,  97.18  ],
       [  1.9558,  94.92  ],
       [  1.9304,  84.976 ],
       [  1.9812,  79.552 ],
       [  2.0066,  79.1   ],
       [  1.9558,  85.88  ],
       [  1.9304,  70.512 ],
       [  1.8796,  81.36  ],
       [  2.0066,  94.92  ],
       [  1.9558,  94.92  ],
       [  1.8034,  79.552 ],
       [  1.9304, 101.248 ],
       [  1.8796, 102.604 ],
       [  1.905 , 104.864 ],
       [  1.905 ,  75.032 ],
       [  1.9558,  89.496 ],
       [  1.905 ,  75.032 ],
       [  1.8288, 110.288 ],
       [  1.9812,  81.812 ],
       [  2.0066, 101.7   ],
       [  1.8796, 106.672 ],
       [  1.9304,  85.428 ],
       [  1.9558, 110.74  ],
       [  1.8034,  78.196 ],
       [  1.9812,  75.936 ],
       [  1.778 ,  93.112 ],
       [  1.9812,  80.004 ],
       [  1.8796,  78.196 ],
       [  1.905 ,  70.06  ],
       [  1.9304, 111.192 ],
       [  1.9812,  91.756 ],
       [  1.8034,  73.224 ],
       [  1.9304,  72.32  ],
       [  1.82

In [ ]:
players_conv[:,0]

(206,)

In [ ]:
tall_players = players_conv[players_conv[:,0] > 1.8]
tall_players

array([[  1.8796,  45.2   ],
       [  1.905 ,  97.18  ],
       [  1.9558,  94.92  ],
       [  1.9304,  84.976 ],
       [  1.9812,  79.552 ],
       [  2.0066,  79.1   ],
       [  1.9558,  85.88  ],
       [  1.9304,  70.512 ],
       [  1.8796,  81.36  ],
       [  2.0066,  94.92  ],
       [  1.9558,  94.92  ],
       [  1.8034,  79.552 ],
       [  1.9304, 101.248 ],
       [  1.8796, 102.604 ],
       [  1.905 , 104.864 ],
       [  1.905 ,  75.032 ],
       [  1.9558,  89.496 ],
       [  1.905 ,  75.032 ],
       [  1.8288, 110.288 ],
       [  1.9812,  81.812 ],
       [  2.0066, 101.7   ],
       [  1.8796, 106.672 ],
       [  1.9304,  85.428 ],
       [  1.9558, 110.74  ],
       [  1.8034,  78.196 ],
       [  1.9812,  75.936 ],
       [  1.9812,  80.004 ],
       [  1.8796,  78.196 ],
       [  1.905 ,  70.06  ],
       [  1.9304, 111.192 ],
       [  1.9812,  91.756 ],
       [  1.8034,  73.224 ],
       [  1.9304,  72.32  ],
       [  1.8288,  79.1   ],
       [  1.95