<a href="https://www.kaggle.com/code/aswin2021/m7l1-ipynb?scriptVersionId=206427561" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<a href="https://colab.research.google.com/github/AswinAzikar/tutedude_assignments/blob/Module_7/m7L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [9]:
arr = np.ones(5)

arr_int= np.ones(5, dtype=int)

print(arr)
print(arr_int)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [10]:
arr.dtype
arr_int.dtype

dtype('int64')

In [18]:
arr_mat = np.ones((2,3),dtype=int)
arr_mat


array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
arr_mat_zro = np.zeros((3,3),dtype=int)
arr_mat_zro

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [23]:
snp.arange(3,500,100)

array([  3, 103, 203, 303, 403])

In [26]:
np.random.randint(6,size=10)

array([0, 4, 0, 0, 5, 3, 0, 2, 0, 1])

In [27]:
np.random.random([3,3])

array([[0.85323291, 0.88839789, 0.54861109],
       [0.7203353 , 0.37444743, 0.99562555],
       [0.72850069, 0.64872373, 0.76236919]])